---
title: "Lab 4 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Setup
1. Login to the lab computer (please don't use your personal computer).  
2. Navigate to github.com and login.   
2. Copy your repository to the desktop.   
5. Copy the class repository to the desktop (https://github.com/jmledford3115/datascibiol).  
6. Copy the files for today's lab from the class repository and paste them into **your** repository.  
7. Open today's lab in RStudio.  

## Review from last time
### *With a partner, discuss the following questions*
1. How is a data frame and how is it different than a data matrix?  
A data frame is a more tabular version of a data matrix, and they are capable of containing more than 1 type of class.

A data frame is an another form of organization, can store more data, look like spreadsheets, and have multiple class types.


2. What is the command we use to import .csv files into R?
<-readr:: read_csv(*name of the file*)
3. Take a moment to show your repository on GitHub to a partner. Can you make any improvements?  
SEEMS GOOD TO ME CHEIF!
## Warm-up
1. In a new R Markdown document, load the tidyverse and a package called `palmerpenguins`.
2. What are the dimensions of the dataset `penguins`?
3. What are the names of the variables in the `penguins` dataset?
4. How many individuals were sampled on each island in the `penguins` dataset?
5. What is the mean body mass for all individuals in the `penguins` dataset?
