---
title: "Lab 2 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Setup
1. Login to the lab computer (please don't use your personal computer).  
2. Navigate to github.com and login.   
2. Copy your repository to the desktop.   
5. Copy the class repository to the desktop (https://github.com/jmledford3115/datascibiol).  
6. Copy the files for today's lab from the class repository and paste them into **your** repository.  
7. Open today's lab in RStudio.  

## Review from last time
### *With a partner, discuss the following questions*
1. What is the association between `R` and `R Studio`?
R studio is a GUI in which it makes R easier to interpret, understand, and write.
2. What is the association between `github.com` and `GitHub Desktop`?  
Github desktop is a program that is associated with the website Github.com. 
It allows for easier access, manipulation, and ability to organize and clone repositories than the website
3. Why do programmers use `GitHub`?
it is a program that allows coders to freely manipulate and interact with code, while not dealing with version mismatches. Github also shows hierarchical files which create a history for udpates
3. What is `R Markdown`? What are the advantages of this format?  
R markdown is a format for non-coders to view and read.This format can be put into presentations, pdfs, htmls, and other ways for represntation of code.
4. How do you insert a new code chunk?  
You look at the top right and see a C+ green button. In that button you are able to see a Rmarkdown file.

## Homework
1. Please open `homework 1`.  
2. With a partner, discuss any problems and fix last-minute issues.  
3. Follow our instructions to push your homework.  
4. Have someone double-check your upload on `github.com`